main: com.bitlimit.pulse.bukkit.PulsePlugin
name: Pulse
version: 0.0.1
author: Kolin Krewinkel
description: Vital.
website: https://github.com/BitLimit/Pulse/
commands:
    pulse:
        description: Unimplemented and implicitly undocumented.
permissions:
    pulse.*:
        description: Gives all permissions of the plugin.
        default: op
    pulse.observe:
        description: Gives permission to receive logging messages.
        default: true
